services:
  postgres:
    container_name: blog_postgres_db
    image: 'postgres:16.0'
    environment:
      - 'POSTGRES_DB=posts'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=dan'
    ports:
      - '5433:5432'